CREATE TABLE users (userid INTEGER NOT NULL, username TEXT COLLATE NOCASE NOT NULL, salt BLOB(32) NOT NULL, verifier BLOB(32) NOT NULL, passwd BLOB(20) NOT NULL, mail TEXT NOT NULL, flag INTEGER NOT NULL, data BLOB NOT NULL, PRIMARY KEY(userid), UNIQUE(username));
CREATE TABLE "friends" (userid INTEGER NOT NULL, friendlist TEXT NOT NULL, PRIMARY KEY(userid));
CREATE TABLE "bans" (userid INTEGER NOT NULL, expire INTEGER NOT NULL, PRIMARY KEY(userid));
